[theme]
base = "light"
primaryColor = "#0891B2"
backgroundColor = "#F7FCFF"
secondaryBackgroundColor = "#EAF9FF"
textColor = "#163247"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
